---
umbilical:
  duto_por_metro: 630
  acessorios_por_tramo: 50.0e+3
  obras_uep: 250.0e+3
  tramos:
    flowline:
      num_tramos: 3
      comp: 2500
    riser:
      num_tramos: 1
      comp: 2255
  pslv:
    diaria: 250.0e+3
    servico: 30.0e+3 # por dia
    vel: 6000 # metros ao dia
    carga: 3 #dias
    pull_in: 12 #horas
    conexao_tramos: 6 #horas/conexao
    cvd: 12 #horas
  pidf:
    diaria: 120.0e+3
    duracao: 5 #dias




