---
#--------------------------
# Parâmetros de Projeto
#--------------------------
capex:
  umbilical:
    duto_por_metro: 1 # custo por metro
    acessorios: 2 # custo por tramo
    obras_uep: 10 # despesa direta
    tramos:
      flowline:
        num_tramos: 3
        comp: 10 # metros
      riser:
        num_tramos: 1
        comp: 15 # metros

  gas_lift:
    duto_por_metro: 2 # custo por metro
    acessorios: 2 # por tramo
    obras_uep: 10 # despesa direta
    tramos:
      flowline:
        num_tramos: 3
        comp: 10 #metros
      riser:
        num_tramos: 1
        comp: 15 #metros

  coleta:
    riser:
      duto_por_metro: 2 # custo por metro
      acessorios: 2 # por tramo
      obras_uep: 10 # despesa direta
      flut: 40 # flutuadores
      num_tramos: 3
      comp: 10 # metros
    flowline:
      A: #flexível
        duto_por_metro: 2 # custo por metro
        acessorios: 1 # por tramo
        num_tramos: # lista
          - 2
          - 1
        comp:
          - 10 # metros 
          - 20 # metros
        anm: 20 # despesa direta
      B: # rígido
        duto_por_metro: 10 # custo por metro
        embarcacao:
          contratacao: 10 # despesa direta
          diaria: 2 # diária da embarcacão
          servico: 1 # por dia
          vel: 2 # metros por dia
        anm: 20 # despesa direta
        plet:
          num: 2
          custo: 5 # por unidade
          vel: 12 # horas por unidade (Instalacão pela embarcacão J-Lay)
        jumper:
          custo: 3
          instalacao: 2 # (realizada por barco de apoio)

  pslv:
    diaria: 10
    servico: 2 # por dia
    vel:
      base: 4.5 # metros ao dia
      coleta: 3 # metros ao dia  (sem considerar os flutuadores) 
    vel_flut: 1 # hora por flutudador
    carga: 3 #dias
    pull_in: 12 #horas
    conexao_tramos: 6 #horas/conexao
    cvd: 12 #horas

  pidf:
    v5:
      diaria: 10
      duracao:
        base: 5 #dias
        coleta:
          riser: 2 #dias
          flow: 4 #dias

opex:
  inspecao:
    pidf:
      anos_restante: 8 # anos 2053 - 2045
      # v4 desprezado no projeto
      v3:
        diaria: 20.0e+3
        duracao: 3 # dias
        periodicidade: 3 # anos
      v2:
        diaria: 120.0e+3
        duracao: 2 # dias
        periodicidade: 3 # anos
      v1:
        diaria: 120.0e+3
        duracao: 5 # dias
        periodicidade:
          flexivel: 5 # anos
          umbilical: 10 # anos
    pidr:
      anos_restante: 7 # anos 2053 - 2046
      diaria: 120.0e+3
      duracao: 5 # dias
      periodicidade: 5 # anos
      interna:
        pig: 200.0e+3 # por corrida
        num_corridas: 2 # por inspecao
        periodicidade: 5 # anos
    equipamentos:
      anm:
        periodicidade: 3 # anos
        diaria: 120.0e+3 # RSV
        duracao: 1 # dia
      plets: # somente para duto rígido (opcão B)
        num: 2
        periodicidade: 3 # anos
        diaria: 120.0e+3 # RSV
        duracao: 12 # horas por equipamento

  intervencao:
    periodicidade: 4 # a cada lwo anos (light workover)
    duracao: 20 # dias
    sonda:
      diaria: 180.0e+3
      servico: 50.0e+3
    material: 5.0e+6
    interrupcao: 50 # dias por intervencao

  inibidores:
    custo: 25 # por litro
    vazao: 50 # litros por dia

  descomissionamento:
    A: 45.0e+6 # flexíveis
    B: 65.0e+6 # flexíveis


